# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '4.1.2'
after_success:
  - export TRAVIS_PASSED=true
  - npm install coveralls --global
  - cat ./coverage/lcov.info | coveralls

# Setup process.env
env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: SSvdhS40YwnMwwaYvQ0gR+Jsfkjo46+DyUxSImTlQjh2X8k5CYR5m79LdrB1J1elzCJuzPLGM8F/OlGpSrgUurRbTkIsZLIcaanXlL6d0R3q+C02adu0whsNeM3lFBZaGhaj9jrLS8wwOxsKFHlFCZCI1lOeVFkqR7s0JGbA24dTevI7gKZGzXaUYVjtXzrqiWpqQZJ555VC08onAO86PTvl7NUaSeS+MB/5u+mLdyTtzuXyfRY7cGLqQtLQSfPJGPkzsE6v+Ode5YYDiX4SR0E+eonbR9U2Ezxm0UKlw3sPkwVtSUE2iRVqAYQUSvYhX5YzS0t2Q3kqg95ItlidqShAME+EDn7FRQP/3/jxTMEw43DAJ5TCA+r2nPGRLtZoSqwxlR4b+WghGyDrqFYKg7X2StF9c12ctI6V2S9sQdmRYy9D8vRShfZhVBRJX2euZLrxY567RSzlBcleLs/lq7l6BnOtjrQeYttI8qPPwtNTkJmLHxFw2QpYLiPzBSNsqVtzQDVy49/56ce2ZmHJsyPOMylIKiCwH51Bs1t7Otvx8LCuit8q1J+oepubyu5llhcfi6B/n8C4fsIuqOXiCIJNwf37HQEU6vHI65IACqf/sXgEm0aOCLyDYXX6EwbfFlX0TbK1IauTQd2nSNKdnSk2TKbSSyN1qY2knD8GdiQ=
    # SAUCE_TOKENS
    - secure: CfkwiW9gIcyQUI37UjWK0ouKwL3Km6J+kUap7QI3q2GIGGbPqFMfNHVexvrrXSF2HLl2jKUTkHyDvNV3l7pOlIo1yopMrj75v4g+KBam5LaRGhptWemrpKfZ660k3UuuIHroFwpNHcAf5lrOss9gp2HSpUn+ip8x1onCZOnqeH/VXAV1y+YvfrbViIK5c+0WWluaS9aSQwbvkZ7Hpea7fwL1INDvDFaZO6Y23yna8HIdVKiF1wSkzuh3c9kxUZ0VZLjBnxPv6j587rgr/3SFKIJdHOYTs2YaBmNQ8Gg9Bo41B9yfITTMYKjMAop+5IlgfhOkKVQnGiRq59zU1gMXHSSkKE+hFm1ujeRIfMMZ1+tC0F2UCXj42+dC2+h5LE62LzCzPxFc/wej4xo3KhXNcFX5lpcQ0mnrAbtWANn10nlMKFEPax/AiWHde2vjkfhOmX9FFTIdXKqKTusn3cui8sVTWYfjaApgnktRumPupuUzClvXQuTsj1ysU1Vqv4IPcPApyLClKfxVI7671lqXhdMDbzq2sK/xmEoxU4CFz8Ko7M02I+wNKAFGx7n/EQZ+xrW25KEWUCsg23RpskPGK7Dy8yrDg8zbbh6SSiOkmx/Ua1Yu4Y+xtWWMvU1ReplqxundL36TUxrePu0CFH7RvqlrDDWhWM2k/vqym5vTa6k=
    - secure: QTtJqcfZuevt9FDuatdofWROe1+9R/fukP2RFY8X7+LwheH/KaCkJFf08cv9aVckCVS1qpPxOmte52XeoJ+vRoM2z67oOb+OxLCebSEe84c0uTJ/iT/aBy9fpiSLJKXMmxRL+g5vMjWRhLaDpIuivI9bDExNkUxr7BsfDrqV3Tpd/JE9lcxnKlrSZfm2HVyL2IhiRXQbqDdTV4QK6BfZSK/7N8iSVGmOnCLI5CKxA1k+iTcLjOY1LrL1oPL+8ayNLzaWnjM5ebKsDNgBEEjAYcDxqX7Fd+TYxj/9lx+vtwBSmnOwVaAzYiMpIJiKWt/wRFmJXv9qJIgMDjnZYCPS/mFX8n7Ex7o/p8v45suHK6A4TETJajO4XYMELgJCxTNBp8y4NsOgDC9z54EeYGQp5uXEBq4eAJbDVrRF/1i93X8fMTn05sQm9g7F1nRQCAO0So17/dfyAiMcud6bvkiRKfy3gwWu2guhVN1nhbA8XN+SVyVrOYATxW2xeiq5gY6aLRPhpXzUaHs3OQioDon6B59346RK/C7ZOW141n8R1pArpbq6wGWkshsGawlyleTsG188U27KlnKcnLaIgx0Mrc8soXyAvk7wChgfW9UqFcWWS93OFNnJzKc4NPPUIM7QlMbqrrdvqmd4os+gf88PrGR8NPiEvPr/WPtec7YseAs=

# Npm publish options
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: lcekuxzybCtlLUDdP3lj4CbLfbK33omszl1KPLUwA361GnoTxaJwjWzMHMN3LF7Bsxau/F6cnQ+q2Icd0K2roxQXwc/1W04AdZUHH3s+FrKmIz4c7m9fs7esXLdfEDTR+U5eIqhzGc9Nj0hqhXIfBLPF+B6+EjFGjw3p1wwveFLrWIP+EJxLRarTAXpRWsqcUd8EwpbXECghNFAeTbv5HiphsgHdUTJpg9cRJ9GJG1q+O5mUqeWfRqW7jneVCVvBP09oLHuhQG1qI7j0vLqWQ8BFyhMJSzvEPN7nucaIL0uMtjL70Y3N4suPoiOfZP2atBkPW75NL+aco+LdUayYfR1SX5qqL7IR2cZRgBE5jYxHBxUUlDQhA2GKnaIco5plHXZWawdsC/+v4xoeQtClbOlcCC4RvMaETtFh1AMgZ3rWljDx+ipNsWG6etfiJFuUuSWBaIrwngVZSP+sU9615Mt2HdKiF4+uITvhzSuatEz7ymfpGtPlFcxhJQW/YvlXcTwbO+DrmZhcZO6UmBuyGcXZ7o2IzmeohWvKJ0Qpc9B0ATXvKHzvWV4PA1St8uV11KygqWGi63cHd3oTYvDSw0zwDlaOfD82eHGYmmmKChUD2/uCJSbFIaquxG+raJ5J5X6fVT9z/rtzdYgfkswWDk5xe4rnFif2QxWwi/DA2PU=
    
  # keep the devDependencies
  skip_cleanup: true

# Cloud testing
after_deploy:
  - npm run test-cloud